#!/usr/bin/env node

let path = require('path')
let lib = require('./lib')

let files = process.argv.slice(2).map(path.normalize)
let fposts = files.filter(lib.is_post).filter(is_md)
let fpages = files.filter( v => !lib.is_post(v)).filter(is_md)

process.stdout.write(JSON.stringify({
    posts: rev_sort_by_file_name(fposts.map(post)),
    pages: fpages.map(page)
}))


function is_md(file) { return '.md' === path.extname(file) }

function post(file) {
    return parse(file, [{
	attr: 'authors',
	fn: v => v.length !== 0
    }])
}

function page(file) { return parse(file) }

function parse(file, required_attrs) {
    let mp = new lib.MarkdownParser(file)
    return Object.assign({file}, mp.front_matter(required_attrs))
}

function rev_sort_by_file_name(arr) {
    return arr.sort( (a, b) => {
	return b.file.localeCompare(a.file)
    })
}
